Initial Proposal
mozilla/bugbug pull request #1917
Opened 2020-11-09 02:37 UTC by RicardormDev

Tbh this is my first try on solving an open source issue, I am not even sure if I understood what I needed to do but I don't have anything to lose. 

I just wrote a function to get the delta between the nightly landing and the uplift time. #38
https://github.com/mozilla/bugbug/issues/38

I hope this works.

2020-11-12 09:54 UTC, ayush-1506 requested changes
Thanks for the PR! Can you setup pre-commit (mentioned in the readme) to ensure that all linting and isort changes are made before committing? Linting tests seem to be failing at the moment.

2020-11-13 05:22 UTC, ayush-1506 reviewed
Looks good! Could you also add a test in tests/test_bug_features ? Then we should be good to go.

2020-11-13 14:13 UTC, RicardormDev commented
Sure

2020-11-19 22:55 UTC, marco-c commented on bugbug/bug_features.py
> +                    ).replace(tzinfo=timezone.utc)
Instead of manually parsing with `strptime`, you can use `dateutil.parser.parse`

2020-11-19 22:56 UTC, marco-c commented on bugbug/bug_features.py
> +                if change["added"].startswith("approval-mozilla"):
This will not only catch requests, but also approvals

2020-11-19 22:56 UTC, marco-c commented on bugbug/bug_features.py
> +                        landing_comments[0]["comment"]["creation_time"],
There might be multiple landings in the same bug, we should measure the time distance between the last landing before the uplift request and the uplift request

2020-11-29 19:24 UTC, RicardormDev commented
Is it possible to test it locally at windows?

2020-12-08 15:27 UTC, marco-c commented
> Is it possible to test it locally at windows?

I haven't ever tried on Windows, so some fixes might be necessary to have everything working there.

2020-12-17 17:14 UTC, marco-c commented
Feel free to reopen if you still intend to work on this.

2020-12-17 17:14 UTC, closed without merging