fix #3821/Use sum() for Boolean Values in Logging Statements.
mozilla/bugbug pull request #3852
Opened 2023-11-25 04:02 UTC by StarKBhaviN

This pull request enhances the logging statements by using the sum() function directly over boolean values. The sum() function efficiently counts the number of True values in a sequence of booleans, providing a more concise and readable approach than traditional methods.

- Also i found some logging statements that using f string formatting.

2023-11-25 19:41 UTC, suhaibmujahid submitted a review, later dismissed
Thank you, @StarKBhaviN! LGTM!

Could you please take care of the following:
- Link to the issue in the PR description instead of the PR title.
- Use a clear title (e.g., "Refactor `sum()` calls to use boolean values directly")
- Update the PR by rebasing or merging from the master branch. This should fix the lint errors.

2023-11-26 05:18 UTC, suhaibmujahid requested changes

2023-11-26 05:18 UTC, suhaibmujahid commented on .pre-commit-config.yaml
This is an unrelated change. Please drop it. When I asked to update the PR, I meant to use git to bring the changes. This can be done by merging the upstream master branch into your branch.

2023-11-26 14:20 UTC, suhaibmujahid requested changes

2023-11-26 14:20 UTC, suhaibmujahid commented on .pre-commit-config.yaml
@StarKBhaviN you can see that the changes in `.pre-commit-config.yaml` are still here: https://github.com/mozilla/bugbug/pull/3852/files


I'm not sure what happened exactly, but there is something went wrong. We could solve this by going a step back and removing all changes that were done after the first commit by executing the following two commands:

```
git reset 8a070650ff583b0ff4acf6d2766ca4ec041ccc92
git checkout .
```

Then, merge the from master using the following command:
```
git pull --no-rebase upstream master
```

Finally, we want to do a force push since we want to ignore the commits in the remote repository:
```
git push -f
```

2023-11-26 14:53 UTC, StarKBhaviN commented on .pre-commit-config.yaml
Okay! Thank You...

2023-11-26 15:32 UTC, suhaibmujahid reviewed
I just noticed cases where the `sum()` call was not refactored:

https://github.com/mozilla/bugbug/blob/7000abb1855dcc5a3c9c4c51012b961546f21de1/bugbug/models/browsername.py#L72-L79

https://github.com/mozilla/bugbug/blob/7000abb1855dcc5a3c9c4c51012b961546f21de1/bugbug/models/needsdiagnosis.py#L83-L90

And others ...

Could you please make sure to refactor all applicable cases?

2023-11-27 15:10 UTC, suhaibmujahid approved these changes
Thank you, @StarKBhaviN! LGTM!

2023-11-27 15:10 UTC, merged